from . import start
from . import back_uz_handler
from . import back_ru_handler
from . import appeal_uz
from . import bot_uzlang_handler
from . import bot_rulang_handler
from . import region_uz_handler
from . import region_ru_handler
from . import expedition_uz_handler
from . import expedition_ru_handler
from . import plot_uz_handler
from . import plot_ru_handler
from . import well_number_uz_handler
from . import well_number_ru_handler
from . import depth_uz_handler
from . import depth_ru_handler
from . import methods_uz_handler
from . import methods_ru_handler
from . import date_uz_handler
from . import date_ru_handler
from . import name_uz_handler
from . import name_ru_handler
from . import position_uz_handler
from . import position_ru_handler
from . import state_number_uz_handler
from . import state_number_ru_handler
from . import drill_type_uz_handler
from . import drill_type_ru_handler
from . import preparation_time_uz_handler
from . import preparation_time_ru_handler
from . import confirmation_uz_handler
from . import confirmation_ru_handler
from . import echo
